databases:
  - name: my_posdb
    plan: free
    databaseName: my_pos
    user: my_pos

services:
  - type: web
    plan: free
    name: my_pos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn my_pos.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_posdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4